spring:
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=utf-8
      username: root
      password: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      testQuery: select 1
    slaver01:
      url: jdbc:mysql://localhost:3306/slaver01?useUnicode=true&characterEncoding=utf-8
      username: root
      password: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      testQuery: select 1
  #spring.jta.enabled=true
  #spring.jta.atomikos.properties.service==com.atomikos.icatch.standalone.UserTransactionServiceFactory
  #spring.jta.atomikos.properties.max-actives=200
  #spring.jta.atomikos.properties.enable-logging=false